// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: game.sql

package query

import (
	"context"
)

const createGame = `-- name: CreateGame :exec
INSERT INTO game (id, status)
VALUES (?, 'active')
`

func (q *Queries) CreateGame(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, createGame, id)
	return err
}

const deleteAllGames = `-- name: DeleteAllGames :exec
DELETE FROM game
`

func (q *Queries) DeleteAllGames(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllGames)
	return err
}

const finishGame = `-- name: FinishGame :exec
UPDATE game SET ended_at = NOW(), status = 'finished' WHERE id = ?
`

func (q *Queries) FinishGame(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, finishGame, id)
	return err
}

const getCurrentGame = `-- name: GetCurrentGame :one
SELECT id, started_at, ended_at, status FROM game WHERE status = 'active' ORDER BY started_at DESC LIMIT 1
`

func (q *Queries) GetCurrentGame(ctx context.Context) (Game, error) {
	row := q.db.QueryRowContext(ctx, getCurrentGame)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
	)
	return i, err
}

const getGameByID = `-- name: GetGameByID :one
SELECT id, started_at, ended_at, status FROM game WHERE id = ? LIMIT 1
`

func (q *Queries) GetGameByID(ctx context.Context, id string) (Game, error) {
	row := q.db.QueryRowContext(ctx, getGameByID, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
	)
	return i, err
}
