// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: game.sql

package query

import (
	"context"
)

const resetGame = `-- name: ResetGame :exec
DELETE FROM hand
`

func (q *Queries) ResetGame(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetGame)
	return err
}
