// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: hand.sql

package query

import (
	"context"
	"database/sql"
)

const addHand = `-- name: AddHand :execresult
INSERT INTO hand (player_id, is_muck, game_id)
VALUES (?, false, ?)
`

type AddHandParams struct {
	PlayerID int32
	GameID   string
}

func (q *Queries) AddHand(ctx context.Context, arg AddHandParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addHand, arg.PlayerID, arg.GameID)
}

const deleteHandAll = `-- name: DeleteHandAll :exec
DELETE FROM hand
`

func (q *Queries) DeleteHandAll(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteHandAll)
	return err
}

const deleteHandByAntennaID = `-- name: DeleteHandByAntennaID :exec
DELETE FROM hand WHERE player_id = (SELECT player_id FROM antenna WHERE antenna.id = ?)
`

func (q *Queries) DeleteHandByAntennaID(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteHandByAntennaID, id)
	return err
}

const deleteHandByGameID = `-- name: DeleteHandByGameID :exec
DELETE FROM hand WHERE game_id = ?
`

func (q *Queries) DeleteHandByGameID(ctx context.Context, gameID string) error {
	_, err := q.db.ExecContext(ctx, deleteHandByGameID, gameID)
	return err
}

const getHand = `-- name: GetHand :one
SELECT id, player_id, equity FROM hand WHERE id = ? LIMIT 1
`

type GetHandRow struct {
	ID       int32
	PlayerID int32
	Equity   sql.NullFloat64
}

func (q *Queries) GetHand(ctx context.Context, id int32) (GetHandRow, error) {
	row := q.db.QueryRowContext(ctx, getHand, id)
	var i GetHandRow
	err := row.Scan(&i.ID, &i.PlayerID, &i.Equity)
	return i, err
}

const getHandBySerial = `-- name: GetHandBySerial :one
SELECT
    hand.id AS hand_id,
    antenna.player_id,
    equity
FROM hand JOIN antenna ON antenna.player_id = hand.player_id
WHERE antenna.serial = ?
`

type GetHandBySerialRow struct {
	HandID   int32
	PlayerID sql.NullInt32
	Equity   sql.NullFloat64
}

func (q *Queries) GetHandBySerial(ctx context.Context, serial string) (GetHandBySerialRow, error) {
	row := q.db.QueryRowContext(ctx, getHandBySerial, serial)
	var i GetHandBySerialRow
	err := row.Scan(&i.HandID, &i.PlayerID, &i.Equity)
	return i, err
}

const getHandNotMucked = `-- name: GetHandNotMucked :many
SELECT id, player_id, equity FROM hand WHERE is_muck = false
`

type GetHandNotMuckedRow struct {
	ID       int32
	PlayerID int32
	Equity   sql.NullFloat64
}

func (q *Queries) GetHandNotMucked(ctx context.Context) ([]GetHandNotMuckedRow, error) {
	rows, err := q.db.QueryContext(ctx, getHandNotMucked)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHandNotMuckedRow
	for rows.Next() {
		var i GetHandNotMuckedRow
		if err := rows.Scan(&i.ID, &i.PlayerID, &i.Equity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHandWithCardByPlayerID = `-- name: GetHandWithCardByPlayerID :one
SELECT
    hand.id AS hand_id,
    hand.player_id,
    hand.is_muck,
    equity,
    card_a.card_suit AS card_a_suit,
    card_a.card_rank AS card_a_rank,
    card_a.is_board AS card_a_is_board,
    card_b.card_suit AS card_b_suit,
    card_b.card_rank AS card_b_rank,
    card_b.is_board AS card_b_is_board
FROM hand
         JOIN card AS card_a ON hand.id = card_a.hand_id
         JOIN card AS card_b ON hand.id = card_b.hand_id
WHERE hand.player_id = ?
  AND card_a.id < card_b.id
`

type GetHandWithCardByPlayerIDRow struct {
	HandID       int32
	PlayerID     int32
	IsMuck       bool
	Equity       sql.NullFloat64
	CardASuit    string
	CardARank    string
	CardAIsBoard bool
	CardBSuit    string
	CardBRank    string
	CardBIsBoard bool
}

func (q *Queries) GetHandWithCardByPlayerID(ctx context.Context, playerID int32) (GetHandWithCardByPlayerIDRow, error) {
	row := q.db.QueryRowContext(ctx, getHandWithCardByPlayerID, playerID)
	var i GetHandWithCardByPlayerIDRow
	err := row.Scan(
		&i.HandID,
		&i.PlayerID,
		&i.IsMuck,
		&i.Equity,
		&i.CardASuit,
		&i.CardARank,
		&i.CardAIsBoard,
		&i.CardBSuit,
		&i.CardBRank,
		&i.CardBIsBoard,
	)
	return i, err
}

const muckHand = `-- name: MuckHand :exec
UPDATE hand SET is_muck = true WHERE id = ?
`

func (q *Queries) MuckHand(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, muckHand, id)
	return err
}

const resetEquity = `-- name: ResetEquity :exec
UPDATE hand SET equity = 0
`

func (q *Queries) ResetEquity(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetEquity)
	return err
}

const updateEquity = `-- name: UpdateEquity :exec
UPDATE hand SET equity = ? WHERE id = ?
`

type UpdateEquityParams struct {
	Equity sql.NullFloat64
	ID     int32
}

func (q *Queries) UpdateEquity(ctx context.Context, arg UpdateEquityParams) error {
	_, err := q.db.ExecContext(ctx, updateEquity, arg.Equity, arg.ID)
	return err
}
