// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: hand_history.sql

package query

import (
	"context"
)

const copyHandsToHistory = `-- name: CopyHandsToHistory :exec
INSERT INTO hand_history (game_id, player_id, equity, is_muck)
SELECT hand.game_id, hand.player_id, hand.equity, hand.is_muck
FROM hand
WHERE hand.game_id = ?
`

func (q *Queries) CopyHandsToHistory(ctx context.Context, gameID string) error {
	_, err := q.db.ExecContext(ctx, copyHandsToHistory, gameID)
	return err
}

const getHandHistoryByGameID = `-- name: GetHandHistoryByGameID :many
SELECT id, game_id, player_id, equity, is_muck, created_at
FROM hand_history
WHERE game_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetHandHistoryByGameID(ctx context.Context, gameID string) ([]HandHistory, error) {
	rows, err := q.db.QueryContext(ctx, getHandHistoryByGameID, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HandHistory
	for rows.Next() {
		var i HandHistory
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.PlayerID,
			&i.Equity,
			&i.IsMuck,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHandHistoryByPlayerID = `-- name: GetHandHistoryByPlayerID :many
SELECT id, game_id, player_id, equity, is_muck, created_at
FROM hand_history
WHERE player_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetHandHistoryByPlayerID(ctx context.Context, playerID int32) ([]HandHistory, error) {
	rows, err := q.db.QueryContext(ctx, getHandHistoryByPlayerID, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HandHistory
	for rows.Next() {
		var i HandHistory
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.PlayerID,
			&i.Equity,
			&i.IsMuck,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
