// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package query

import (
	"database/sql"
	"time"
)

type Antenna struct {
	ID            int32
	Serial        string
	AntennaTypeID int32
	PlayerID      sql.NullInt32
}

type AntennaType struct {
	ID   int32
	Name string
}

type Card struct {
	ID       int32
	CardSuit string
	CardRank string
	IsBoard  bool
	HandID   sql.NullInt32
	Serial   string
	GameID   sql.NullString
}

type Game struct {
	ID        string
	StartedAt time.Time
	EndedAt   sql.NullTime
	Status    string
}

type Hand struct {
	ID       int32
	PlayerID int32
	Equity   sql.NullFloat64
	IsMuck   bool
	GameID   sql.NullString
}

type Player struct {
	ID   int32
	Name string
}
