// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package query

import (
	"database/sql"
)

type Player struct {
	ID       int64
	Name     string
	HandType string
	Hands    string
	Equity   sql.NullFloat64
}
