// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: player.sql

package query

import (
	"context"
	"database/sql"
)

const addPlayer = `-- name: AddPlayer :execresult
INSERT INTO player (name)
VALUES (?)
`

func (q *Queries) AddPlayer(ctx context.Context, name string) (sql.Result, error) {
	return q.db.ExecContext(ctx, addPlayer, name)
}

const deletePlayerWithHandWithCards = `-- name: DeletePlayerWithHandWithCards :exec
DELETE FROM card
WHERE hand_id IN (SELECT id FROM hand WHERE player_id = ?)
`

func (q *Queries) DeletePlayerWithHandWithCards(ctx context.Context, playerID int32) error {
	_, err := q.db.ExecContext(ctx, deletePlayerWithHandWithCards, playerID)
	return err
}

const getPlayer = `-- name: GetPlayer :one
SELECT id, name FROM player
WHERE id = ? LIMIT 1
`

func (q *Queries) GetPlayer(ctx context.Context, id int32) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayer, id)
	var i Player
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getPlayerBySerial = `-- name: GetPlayerBySerial :one
SELECT player.id, player.name
FROM player
JOIN antenna ON player.id = antenna.player_id
WHERE antenna.serial = ? LIMIT 1
`

func (q *Queries) GetPlayerBySerial(ctx context.Context, serial string) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayerBySerial, serial)
	var i Player
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getPlayerWithDevice = `-- name: GetPlayerWithDevice :one
SELECT player.id, player.name, antenna.serial
FROM player
JOIN antenna ON player.id = antenna.player_id
WHERE player.id = ? LIMIT 1
`

type GetPlayerWithDeviceRow struct {
	ID     int32
	Name   string
	Serial string
}

func (q *Queries) GetPlayerWithDevice(ctx context.Context, id int32) (GetPlayerWithDeviceRow, error) {
	row := q.db.QueryRowContext(ctx, getPlayerWithDevice, id)
	var i GetPlayerWithDeviceRow
	err := row.Scan(&i.ID, &i.Name, &i.Serial)
	return i, err
}

const getPlayersWithDevice = `-- name: GetPlayersWithDevice :many
SELECT player.id, player.name, antenna.serial
FROM player
JOIN antenna ON player.id = antenna.player_id
`

type GetPlayersWithDeviceRow struct {
	ID     int32
	Name   string
	Serial string
}

func (q *Queries) GetPlayersWithDevice(ctx context.Context) ([]GetPlayersWithDeviceRow, error) {
	rows, err := q.db.QueryContext(ctx, getPlayersWithDevice)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlayersWithDeviceRow
	for rows.Next() {
		var i GetPlayersWithDeviceRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Serial); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayersWithHand = `-- name: GetPlayersWithHand :many
SELECT
    player.id,
    player.name,
    hand.id AS hand_id,
    hand.equity,
    hand.is_muck,
    card_a.card_suit AS card_a_suit,
    card_a.card_rank AS card_a_rank,
    card_a.is_board AS card_a_is_board,
    card_b.card_suit AS card_b_suit,
    card_b.card_rank AS card_b_rank,
    card_b.is_board AS card_b_is_board
FROM player
         INNER JOIN hand ON player.id = hand.player_id
         INNER JOIN card AS card_a ON hand.id = card_a.hand_id
         INNER JOIN card AS card_b ON hand.id = card_b.hand_id
WHERE hand.is_muck = false
  AND card_a.id < card_b.id
`

type GetPlayersWithHandRow struct {
	ID           int32
	Name         string
	HandID       int32
	Equity       sql.NullFloat64
	IsMuck       bool
	CardASuit    string
	CardARank    string
	CardAIsBoard bool
	CardBSuit    string
	CardBRank    string
	CardBIsBoard bool
}

func (q *Queries) GetPlayersWithHand(ctx context.Context) ([]GetPlayersWithHandRow, error) {
	rows, err := q.db.QueryContext(ctx, getPlayersWithHand)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlayersWithHandRow
	for rows.Next() {
		var i GetPlayersWithHandRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.HandID,
			&i.Equity,
			&i.IsMuck,
			&i.CardASuit,
			&i.CardARank,
			&i.CardAIsBoard,
			&i.CardBSuit,
			&i.CardBRank,
			&i.CardBIsBoard,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlayerName = `-- name: UpdatePlayerName :execresult
UPDATE player
SET name = ?
WHERE id = ?
`

type UpdatePlayerNameParams struct {
	Name string
	ID   int32
}

func (q *Queries) UpdatePlayerName(ctx context.Context, arg UpdatePlayerNameParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updatePlayerName, arg.Name, arg.ID)
}
