name: Test
on:
  push:
    branches:
      - "**"
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Lint
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...
      - name: Test (back / Go)
        run: |
          go test ./...
      - name: Test (front / Next.js)
        run: |
          cd ui/
          npm install
          npm run lint
      - name: Test (Platform.io / C++)
        run: |
          cd clients/m5stack
          pio run